trigger:
- ubuntu-branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NuGetToolInstaller@1
  
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
    
  - task: Bash@3
    displayName: Veracode Package
    inputs:
      targetType: 'inline'
      script: |
        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
        ./veracode package --source ./ --output $(build.artifactstagingdirectory)/verascan --trust

  - task: Bash@3
    displayName: Veracode IAC Analysis
    inputs:
      azureSubscription: 'veracode_scan'
      targetType: 'inline'
      script: |     
        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
        ./veracode scan --type directory --source ./ --format table | tee iac-scan.table
        ### Uncomment the following line for failing build on IAC / Container findings
        # grep "Policy Passed = true" iac-scan.table
     env:
       VERACODE_API_ID: '$(VERACODE_API_ID)'
       VERACODE_API_KEY: '$(VERACODE_API_KEY)'
    
  - task: Veracode@3
    displayName: Veracode Policy Scan
    inputs:
      ConnectionDetailsSelection: 'Endpoint'
      AnalysisService: 'veracode_scan'
      veracodeAppProfile: '$(Build.Repository.Name)'
      version: '$(Build.BuildNumber)'
      filepath: '$(build.artifactstagingdirectory)/verascan'
      createProfile: true
      importResults: false
      #maximumWaitTime: '45'
      #failBuildOnPolicyFail: true
      optargs: '-criticality high -deleteincompletescan 2'
